import UiText from "../components/UiText";
import { graphEdges, graphNodes } from "../data/dummy";
import { Network, Shield, Users } from "../components/icons";
import { useLocale } from "../context/LocaleContext";

export default function NetworkPage({onNavigate}:{onNavigate:(page:string,param?:string)=>void}) {
  const {locale}=useLocale(); const degree=Object.fromEntries(graphNodes.map(n=>[n.id,0])); graphEdges.forEach(e=>{degree[e.source]=(degree[e.source]||0)+1;degree[e.target]=(degree[e.target]||0)+1});
  const ranked=graphNodes.map(n=>({...n,connections:degree[n.id]||0,evidence:n.id==="PERSON-P004"?3:Math.max(1,Math.ceil((degree[n.id]||0)/2))})).sort((a,b)=>b.connections-a.connections).slice(0,8);
  return <div className="min-h-screen bg-[var(--color-base-bg)]"><header className="bg-[var(--color-surface)] border-b border-[var(--color-border-subtle)] p-6"><div className="max-w-[1200px] mx-auto"><h1 className="text-3xl">{locale==="hi"?"नेटवर्क विश्लेषण":"Network analysis"}</h1><p className="text-[var(--color-text-secondary)] mt-1">CASE-2026-017 · Operation Nightfall · {locale==="hi"?"संबंध संकेत, दोष का निष्कर्ष नहीं":"relationship indicators, not conclusions of guilt"}</p></div></header><div className="max-w-[1200px] mx-auto p-6 grid grid-cols-1 lg:grid-cols-3 gap-6"><section className="lg:col-span-2 gov-panel overflow-hidden"><div className="p-5 border-b border-[var(--color-border-subtle)]"><h2 className="font-bold"><UiText>Connection ranking</UiText></h2></div>{ranked.map((n,i)=><button key={n.id} onClick={()=>n.type==="person"&&onNavigate("person",n.id)} className="w-full grid grid-cols-[32px_1fr_90px_90px] gap-3 p-4 text-left border-b border-[var(--color-border-subtle)] hover:bg-[var(--color-surface-hover)]"><span className="font-mono text-[var(--color-text-muted)]">{String(i+1).padStart(2,"0")}</span><span><strong><UiText>{n.label}</UiText></strong><small className="block uppercase text-[10px] text-[var(--color-text-muted)]"><UiText>{n.type}</UiText></small></span><span className="font-mono">{n.connections}<UiText> links</UiText></span><span className="font-mono">{n.evidence}<UiText> sources</UiText></span></button>)}</section><aside className="space-y-4"><div className="gov-panel p-5 border-t-[3px] border-t-[var(--color-saffron)]"><Network className="text-[var(--color-primary)]"/><h2 className="font-bold mt-3"><UiText>Bridge entity</UiText></h2><p className="font-mono text-sm mt-2">PERSON-P004 · Vikram Singh</p><p className="text-sm text-[var(--color-text-secondary)] mt-3"><UiText>Connects Vehicle V001 with fictional cross-case record CASE-X007 through EV-2026-0007.</UiText></p></div><div className="gov-panel p-5"><Shield className="text-[var(--color-success)]"/><h2 className="font-bold mt-3"><UiText>Responsible interpretation</UiText></h2><p className="text-sm text-[var(--color-text-secondary)] mt-2"><UiText>Centrality and bridge metrics prioritize review. They do not predict criminality.</UiText></p></div><button className="btn-premium w-full" onClick={()=>onNavigate("graph")}><Users size={15}/><UiText>Inspect graph</UiText></button></aside></div></div>;
}

